version: '3'

vars:
  UI: ./web
  BACKEND: ./server

tasks:

  ui:
    desc: Run only the frontend
    cmds: 
      - cd {{.UI}} && bun run dev

  ui-prod:
    desc: Run only the frontend in production mode
    cmds:
      - cd {{.UI}} && bun run build && bun run preview

  server:
    desc: Run only the backend
    cmds: 
      - cd {{.BACKEND}} && gradle bootRun -Dspring.profiles.active=dev

  server-prod:
    desc: Run backend in production mode
    cmds:
      - cd {{.BACKEND}} && gradle bootRun -Dspring.profiles.active=prod

  db:
    desc: Start the database
    cmds:
      - docker compose up -d

  db-stop:
    desc: Stop the database
    cmds:
      - docker compose down

  db-destroy:
    desc: Destroy the database
    cmds:
      - docker compose down -v

  psql: 
    desc: Connect to the database
    cmds:
      - docker exec -it postgres-db psql -U postgres

  dev: 
    desc: Run the full application in development mode
    cmds:
      - task: db
      - task: server
      - task: ui

  prod: 
    desc: Run the full application in production mode
    cmds:
      - task: db
      - task: server-prod
      - task: ui-prod