spring:
  application:
    name: bird

  config:
    import: optional:file:.env.properties

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
    
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      initialization-fail-timeout: 60000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update # Disable in prod
    properties:
      hibernate:
        format_sql: true
    show-sql: false

  sql:
    init:
      mode: never

logging:
  level:
    root: WARN
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF


jwt:
  access-secret: ${ACCESS_SECRET}
  refresh-secret: ${REFRESH_SECRET}

frontend:
  url: ${FRONTEND_URL}